New methods
yana-glt/Banks pull request #2
Opened 2022-12-08 09:50 UTC by yana-glt

Request to merge main branch with branch new_methods (+equals, hashcode, toString, Interfaces, Exceptions, Log4j)

2022-12-09 12:21 UTC, vboltrukanis requested changes

2022-12-09 12:21 UTC, vboltrukanis commented on .idea/misc.xml
> +<?xml version="1.0" encoding="UTF-8"?>
add .idea bin target ...
all unwanted files should be controlled by .gitignore file

2022-12-09 12:21 UTC, vboltrukanis commented on .idea/misc.xml
> +<?xml version="1.0" encoding="UTF-8"?>
also logs

2022-12-09 12:21 UTC, vboltrukanis commented on src/Main.java
> +//		System.out.println(krakowBranch.getId());
remove unused comments

2022-12-09 12:21 UTC, vboltrukanis commented on src/branches/Employee.java
> +	public static void setNumberOfEmployees(int numberOfEmployees) {
this method actually breaks the entire logic of what you intended to do, remove it.

2022-12-09 12:21 UTC, vboltrukanis commented on src/clients/Client.java
> +		return this.id == other.id && (this.identificationNumber == other.identificationNumber
not really readable, try to refactor this

2022-12-09 12:21 UTC, vboltrukanis commented on src/branches/Branch.java
> +
no need for this line

2022-12-09 12:21 UTC, vboltrukanis commented on src/branches/Department.java
> +
unnecessary empty line

2022-12-09 12:21 UTC, vboltrukanis commented on src/branches/INotifyClients.java
> +				// e.printStackTrace();
remove it if you don't need it

2022-12-09 12:21 UTC, vboltrukanis commented on src/products/Currency.java
> +	EUR, USD, GBP, PLN, DKK, NOK, SEK, CZK, HUF, GEL, TRY, CHF, JPY, CNY
add some parameters to this enum, so values differs not only by the names.

2022-12-10 20:06 UTC, yana-glt commented on .idea/misc.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Can you explain in more detail what you mean

2022-12-10 20:10 UTC, yana-glt commented on src/Main.java
> +//		System.out.println(krakowBranch.getId());
The commented code is used when demonstrating the project and checking the operation of methods and exceptions in the Main class. Therefore, I would prefer to leave it for now if possible.

2022-12-10 20:20 UTC, yana-glt commented on src/branches/Branch.java
> +
Excuse me, can you clarify which line I should remove.

2022-12-10 20:57 UTC, yana-glt commented on src/clients/Client.java
> +		return this.id == other.id && (this.identificationNumber == other.identificationNumber
Do you mean refactoring all eguals methods in the project (because
 I use the same approach everywhere), or specifically this one? If so, let me clarify, do you not like the name of the variables, or rather the ternary operator makes the method unreadable?

2022-12-10 21:06 UTC, yana-glt commented on src/products/Currency.java
> +	EUR, USD, GBP, PLN, DKK, NOK, SEK, CZK, HUF, GEL, TRY, CHF, JPY, CNY
If you allow, I will add this in the next homework (possibly with new business related methods)

2022-12-10 21:17 UTC, yana-glt commented on src/branches/Employee.java
> +	public static void setNumberOfEmployees(int numberOfEmployees) {
OK. Deleted it

2022-12-10 21:17 UTC, yana-glt commented on src/branches/Branch.java
> +
ok

2022-12-10 21:17 UTC, yana-glt commented on src/branches/Department.java
> +
ok

2022-12-12 11:11 UTC, yana-glt commented on .idea/misc.xml
> +<?xml version="1.0" encoding="UTF-8"?>
I got it already

2022-12-12 21:59 UTC, vboltrukanis requested changes
files from bin and idea folders should not be in github.
Search for:
"gitignore commited files from github"

2022-12-12 21:59 UTC, vboltrukanis commented on src/clients/Client.java
> +		return this.id == other.id && (this.identificationNumber == other.identificationNumber
those multiline return statement is really hard to read, make it more readable and scan the project to find and fix similar issues.

2022-12-13 13:27 UTC, yana-glt commented on src/clients/Client.java
> +		return this.id == other.id && (this.identificationNumber == other.identificationNumber
ok

2022-12-15 12:59 UTC, vboltrukanis requested changes

2022-12-15 12:59 UTC, vboltrukanis commented on src/Main.java
> +
unwanted empty line

2022-12-15 12:59 UTC, vboltrukanis commented on src/branches/Department.java
> +		this.departmentId = ++numberOfDepartments;
Well done! Thanks!

2022-12-15 12:59 UTC, vboltrukanis commented on src/branches/Department.java
> +	public void setDepartmentId(int departmentId) {
we should remove this method, since it makes it possible to break uniqueness of id. If you still allow to do that, maybe we better add some Logger here, to be able to see in logs that someone forced id to change for the exact department.

2022-12-15 12:59 UTC, vboltrukanis commented on src/branches/Employee.java
> +		boolean idEquality = (this.id == other.id);
isIdEqual

2022-12-15 12:59 UTC, vboltrukanis commented on src/branches/Employee.java
> +		boolean idEquality = (this.id == other.id);
boolean variable names start from is/has/should

2022-12-15 12:59 UTC, vboltrukanis commented on src/branches/Employee.java
> +		return idEquality && nameEquality && surnameEquality && dateOfBirthEquality;
This is much better, great!

2022-12-15 12:59 UTC, vboltrukanis commented on src/clients/CorporateClient.java
> +					.println(String.format("Client %s can get a credit, but collateral is required.", this.getName()));
format this)

2022-12-15 12:59 UTC, vboltrukanis commented on src/clients/IndividualClient.java
> +			return false;
```suggestion
		if ((!super.equals(obj)) || (getClass() != obj.getClass()) || (this.hashCode() != obj.hashCode()))
			return false;
```
Those conditions are short and easy to read so we can make it oneliner.

2022-12-15 12:59 UTC, vboltrukanis commented on src/exception_handlers/AccountAlreadyBlockedException.java
> +	}
```suggestion
	public AccountAlreadyBlockedException(Account account) {
		super(String.format("Account %s is already blocked, can not proceed operation!", account.getAccountNumber()));
	}
```

2022-12-15 12:59 UTC, vboltrukanis commented on src/products/accounts/Account.java
> +	public Currency getAccountCurrency() {
```suggestion
	public String getAccountCurrency() {
	    return accountCurrency.getName();
	}
```
You can use it like this.

2022-12-18 23:04 UTC, yana-glt commented on src/branches/Department.java
> +	public void setDepartmentId(int departmentId) {
I will delete

2022-12-18 23:15 UTC, yana-glt commented on src/branches/Employee.java
> +		boolean idEquality = (this.id == other.id);
ok

2022-12-18 23:17 UTC, yana-glt commented on src/clients/CorporateClient.java
> +					.println(String.format("Client %s can get a credit, but collateral is required.", this.getName()));
This is something new) Maybe because of the transition from eclipse to intellij. Don't know...

2022-12-18 23:18 UTC, yana-glt commented on src/clients/IndividualClient.java
> +			return false;
ok

2022-12-18 23:29 UTC, yana-glt commented on src/exception_handlers/AccountAlreadyBlockedException.java
> +	}
I have already made some changes to Exceptions to make them more interesting and informative in the next homework, in the generics branch.

2022-12-18 23:36 UTC, yana-glt commented on src/products/accounts/Account.java
> +	public Currency getAccountCurrency() {
ok

2022-12-21 13:51 UTC, vboltrukanis commented on src/Main.java
> +			logger.warn(e);
we can move this log to assessSolvency method or maybe even to a constructor of this exception. Logs are defined by developers to help developers, they should not be configured in Main. Main kinda represents how client works with your application, have yoy ever add logs to an application that you use?

2022-12-21 13:54 UTC, vboltrukanis commented on src/branches/Employee.java
> +		boolean isNameEqual = (this.name == null && other.name == null)
Just a suggestion to think about, no need to fix:
Maybe here we can replace && with || . So for example when for some user name is not known, we might expect that some other object related to the same Employee might contain name, so we will return true in this case.

2022-12-21 13:56 UTC, vboltrukanis commented on src/branches/INotifyClients.java
> +	default void notifyAllClients(ArrayList<Client> clients, String nameOfMessageFile) {
maybe we can overload this function to also accept `ArrayList<Client> clients, String message` or even create a Enum like
```
GreetingMessage: "Hello dear user ...",
PolicyUpdateMessage: "HI, we currently updated our ..."
...
```
And then we can also overload like 
`ArrayList<Client> clients, MessageType clientMessageType`

2022-12-21 13:58 UTC, vboltrukanis commented on src/branches/INotifyClients.java
> +				logger.warn(e);
```suggestion
				logger.warn(String.format("Message template not found while sending message to %s, message wasn't sent", cl.getEmailAdress()));
```

2022-12-21 14:03 UTC, vboltrukanis approved these changes
Just a few suggestion, good in general. You can merge as soon as u ready.

2022-12-22 10:57 UTC, yana-glt commented on src/Main.java
> +			logger.warn(e);
no, this is my first encounter with loggers.
the accessSolvency() method is called inside the giveCredit() method to evaluate the customer's creditworthiness and automatically issue a credit. In the same place, in giveCredit(), the exception is handled in try/catch. I called the accessSolvency() method on Main just to test the method. Further, this code is commented out all the time (in the following branches), so I'll just delete it.

2022-12-22 11:11 UTC, yana-glt commented on src/branches/Employee.java
> +		boolean isNameEqual = (this.name == null && other.name == null)
I agree that it makes sense. But it seems to me that in the situation with banks, strict logic should be observed with the preservation of personal data. If this can somehow work for bank employees, as you describe, and be useful, then it should not work that way for clients. We shouldn't create a product for a client without setting all his personal data, I think.

2022-12-22 11:16 UTC, yana-glt commented on src/branches/INotifyClients.java
> +	default void notifyAllClients(ArrayList<Client> clients, String nameOfMessageFile) {
Great idea, thanks. I'll think about how to implement this.

2022-12-22 11:19 UTC, yana-glt commented on src/branches/INotifyClients.java
> +				logger.warn(e);
ok

2022-12-22 11:33 UTC, merged