Generics
yana-glt/Banks pull request #3
Opened 2022-12-12 18:36 UTC by yana-glt

2022-12-13 13:27 UTC, vboltrukanis commented
Edit this PR, so that destination branch is `new_methods`. This way we will see only changes related to this PR. Thanks in advance

2022-12-14 15:06 UTC, yana-glt commented
Hello,
I understand what you mean. I changed the branch and added a new commit
with changes in Exceptions to generics branch.

вт, 13 дек. 2022 г. в 14:56, Yana Galitsyna ***@***.***>:

> Excuse me, do you mean swap branches here?
>>
>
> вт, 13 дек. 2022 г. в 14:28, vboltrukanis ***@***.***>:
>
>> Edit this PR, so that destination branch is new_methods. This way we
>> will see only changes related to this PR. Thanks in advance
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/yana-glt/Banks/pull/3#issuecomment-1348545929>, or
>> unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/A2PKG7Z7KXGFETH75D2KSYTWNB2WJANCNFSM6AAAAAAS4IWKJQ>
>> .
>> You are receiving this because you authored the thread.Message ID:
>> ***@***.***>
>>
>

2022-12-15 13:47 UTC, vboltrukanis requested changes

2022-12-15 13:47 UTC, vboltrukanis commented on src/branches/Branch.java
> +	public static <T> T getLastElementOfList(ArrayList<T> list) {
Thats a strange method here)

2022-12-15 13:47 UTC, vboltrukanis commented on src/clients/IndividualClient.java
> +
addCredit() ?
removeCredit() ?

2022-12-15 13:47 UTC, vboltrukanis commented on src/products/accounts/Account.java
> +	public void setResponsibleExecutorOfBloking(Employee responsibleExecutorOfBloking) {
this should be set in setBlock() function. We dont want to allow change of such important data easily.

2022-12-15 13:47 UTC, vboltrukanis commented on src/products/accounts/Account.java
> +		System.out.println(sum);
Some more info here maybe.

2022-12-15 13:47 UTC, vboltrukanis commented on src/products/accounts/Account.java
> +	public static boolean transferMoney(Account srcAccount, Account dstAccount, float transferAmount) {
i believe we should handle exceptions from small function here, and use throws in deduceBalance and refillBalance.

2022-12-15 13:47 UTC, vboltrukanis commented on src/products/cards/IndividualClientsCard.java
> +	public void setClient(IndividualClient client) {
Unlikely we ever will want to change the client of a card, so this method kinda conflicts with business logic.

2022-12-18 23:47 UTC, yana-glt commented on src/branches/Branch.java
> +	public static <T> T getLastElementOfList(ArrayList<T> list) {
OK. I'll get rid of it)

2022-12-19 00:29 UTC, yana-glt commented on src/clients/IndividualClient.java
> +
I implemented adding a new credit to the list of client credits in the giveCredit() method and added the closeCredit() method, in which the credit is removed from the list when the debt is paid in full.

2022-12-19 00:36 UTC, yana-glt commented on src/products/accounts/Account.java
> +	public void setResponsibleExecutorOfBloking(Employee responsibleExecutorOfBloking) {
I don't quite understand what you mean. I already have a blockAccount() method in the Account class that is responsible for blocking. And in it I use the setResponsibleExecutorOfBloking() method to set the responsible executor.

2022-12-19 00:40 UTC, yana-glt commented on src/products/cards/IndividualClientsCard.java
> +	public void setClient(IndividualClient client) {
Agree. It makes sense

2022-12-19 01:43 UTC, yana-glt commented on src/products/accounts/Account.java
> +	public static boolean transferMoney(Account srcAccount, Account dstAccount, float transferAmount) {
I tried to implement this. But it still looks cumbersome, because it is necessary to provide that if the first account is not blocked and money is debited from it, and the second account turns out to be blocked, then it is necessary to roll back the operation on the first account.

2022-12-19 01:57 UTC, yana-glt commented on src/products/accounts/Account.java
> +		System.out.println(sum);
ok

2022-12-21 15:46 UTC, vboltrukanis approved these changes
Minor changes. Plz review them and fix if you believe this is needed before merge.

2022-12-21 15:46 UTC, vboltrukanis commented on src/clients/CorporateClient.java
> +    private String directorsPhoneNumber;
director is an Employee as far as i understand, so here you can just reference related object, instead of hardcoding this data

2022-12-21 15:46 UTC, vboltrukanis commented on src/products/cards/Card.java
> +    public void determineCardExpirationDate() {
this can be private and called inside of cinstructor

2022-12-21 15:46 UTC, vboltrukanis commented on src/products/cards/Card.java
> +        this.setStatus(false);
you can add logger here, as it is important operation.

2022-12-21 15:46 UTC, vboltrukanis commented on src/products/cards/Card.java
> +            this.blockOnRequest();
Thats strange from a perspective of business logic. Maybe we can send a string like blockReason as a param to make it more understandable.

2022-12-22 11:40 UTC, yana-glt commented on src/clients/CorporateClient.java
> +    private String directorsPhoneNumber;
The director is an employee of his company, but not of the bank. The classes Branch, Department and Employee refer specifically to the organization of processes in the bank. I would not like to confuse these two hierarchies.

2022-12-22 11:48 UTC, yana-glt commented on src/products/cards/Card.java
> +    public void determineCardExpirationDate() {
I fixed it

2022-12-22 12:08 UTC, yana-glt commented on src/products/cards/Card.java
> +        this.setStatus(false);
ok

2022-12-22 12:10 UTC, yana-glt commented on src/products/cards/Card.java
> +            this.blockOnRequest();
I added this information to the logger

2022-12-22 13:47 UTC, merged