Add methods for writing/reading to/from a file
yana-glt/Banks pull request #4
Opened 2022-12-18 22:46 UTC by yana-glt

2022-12-19 12:07 UTC, vboltrukanis requested changes

2022-12-19 12:07 UTC, vboltrukanis commented on src/main/java/com/solvd/banks/Main.java
> +    public static void readFromFile() {
move file related methods to FileUtils class

2022-12-19 12:07 UTC, vboltrukanis commented on src/main/java/com/solvd/banks/Main.java
> +}
empty line at the end of file

2022-12-19 22:28 UTC, yana-glt commented on src/main/java/com/solvd/banks/Main.java
> +    public static void readFromFile() {
ok

2022-12-19 22:28 UTC, yana-glt commented on src/main/java/com/solvd/banks/Main.java
> +}
ok

2022-12-21 15:58 UTC, vboltrukanis requested changes

2022-12-21 15:58 UTC, vboltrukanis commented on src/main/java/com/solvd/banks/FileUtils.java
> +    public static void readFromFile() {
filename can be passed as a parameter, to make it more readable. You can also override this function with no parameters and set a default path as info.txt in this case.

2022-12-21 15:58 UTC, vboltrukanis commented on src/main/java/com/solvd/banks/FileUtils.java
> +}
Just as an additional task, which you can perform in new PR in case you wish to: 
ad encryption to a files that save information, so that they are not readable just be reviewing files, but they can be read inside the program and maybe used somehow. [link](https://docs.oracle.com/javase/8/docs/api/javax/crypto/Cipher.html)

2023-01-08 20:38 UTC, yana-glt commented on src/main/java/com/solvd/banks/FileUtils.java
> +    public static void readFromFile() {
ok

2023-01-08 20:42 UTC, yana-glt commented on src/main/java/com/solvd/banks/FileUtils.java
> +}
Okay, I'll try to figure out how to do it. 
Can I merge this branch into the main branch now?

2023-01-11 13:18 UTC, vboltrukanis approved these changes

2023-01-11 15:19 UTC, merged